Repository Chimoney/chimoney-community-projects, pull requests merged in 2023-10, with the labels that each got.

#140 Update README.md
  README.md
Labels: hacktoberfest

#186 Added the blog link in README.md.
  submissions/simple_blog/README.md
Labels: hacktoberfest

#200 Update README.md
  README.md
Labels: hacktoberfest

#192 Info API Wrapper Refactoring
  submissions/Chimoney-Python/chimoney/Info.py
  submissions/Chimoney-Python/chimoney/Payouts.py
Labels: hacktoberfest

#191 Payout API Wrapper Updates
  submissions/Chimoney-Python/chimoney/Payouts.py
Labels: hacktoberfest

#274 Fixed the redirection to CONTRIBUTING.md in README.md
  README.md
Labels: hacktoberfest

#290 Chimoney Telegram Bot
  submissions/telegram-bot-node/package.json
  submissions/telegram-bot-node/src/.env
  submissions/telegram-bot-node/src/payments.json
  submissions/telegram-bot-node/src/start.js
  submissions/telegram-bot-node/src/users.json
Labels: hacktoberfest

#281 Hacktoberfest community project : Secret Santa
  submissions/secret-santa/.gitignore
  submissions/secret-santa/README.md
  submissions/secret-santa/app/globals.css
  submissions/secret-santa/app/home/page.js
  submissions/secret-santa/app/layout.js
  submissions/secret-santa/app/page.js
  submissions/secret-santa/components/PaymentPopup.js
  submissions/secret-santa/components/chimoneypaymentpopup.js
  submissions/secret-santa/components/paymentverification.js
  submissions/secret-santa/jsconfig.json
  submissions/secret-santa/next.config.js
  submissions/secret-santa/package-lock.json
  submissions/secret-santa/package.json
  submissions/secret-santa/postcss.config.js
  submissions/secret-santa/public/images/santa-molang.gif
  submissions/secret-santa/tailwind.config.js
  submissions/secret-santa/utility/index.js
Labels: hacktoberfest, Developer API

#295 Created pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: hacktoberfest

#279 [fix] #278 : Fixed link to LICENSE.md file in README.md
  README.md
Labels: hacktoberfest

#299 Chimoney Whatsapp Bot using Nodejs
  submissions/whatsapp-bot-node/.env
  submissions/whatsapp-bot-node/index.js
  submissions/whatsapp-bot-node/package.json
  submissions/whatsapp-bot-node/payments.json
  submissions/whatsapp-bot-node/readme.md
Labels: hacktoberfest

#270 Fixed repetition Of Chimoney Payout Airtime background based on issue #261
  submissions/chimoney-payout-airtime/src/App.css
  submissions/chimoney-payout-airtime/src/style.js
Labels: hacktoberfest, hacktoberfest-accepted

#301 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest

#247 Create README-JP.md
  README-JP.md
  README.md
Labels: hacktoberfest

#321 Fixed Responsiveness Issue Of Chimoney Payout Airtime Based On Issue #314
  submissions/chimoney-payout-airtime/public/index.html
  submissions/chimoney-payout-airtime/src/style.js
Labels: hacktoberfest, hacktoberfest-accepted

#320 Add Sandbox Option to BaseAPI for Environment Switching(Python SDK)
  submissions/Chimoney-Python/chimoney/Base.py
  submissions/Chimoney-Python/chimoney/Chimoney.py
  submissions/Chimoney-Slackbot-V2/.gitignore
  submissions/Chimoney-Slackbot-V2/Dockerfile
  submissions/Chimoney-Slackbot-V2/README.md
  submissions/Chimoney-Slackbot-V2/modules/choices.py
  submissions/Chimoney-Slackbot-V2/modules/sendchimoney.py
  submissions/Chimoney-Slackbot-V2/modules/validators.py
  submissions/Chimoney-Slackbot-V2/requirements.txt
  submissions/Chimoney-Slackbot-V2/slackbot.py
  submissions/Chimoney-Slackbot-V2/tests/__init__.py
  submissions/Chimoney-Slackbot-V2/tests/validator_tests.py
  submissions/Chimoney-Slackbot/.gitignore
  submissions/Chimoney-Slackbot/Readme.md
  submissions/Chimoney-Slackbot/main.py
  submissions/Chimoney-Slackbot/utils/__pycache__/functions.cpython-39.pyc
  submissions/Chimoney-Slackbot/utils/app/__init__.py
  submissions/Chimoney-Slackbot/utils/app/__pycache__/__init__.cpython-39.pyc
  submissions/Chimoney-Slackbot/utils/app/__pycache__/models.cpython-39.pyc
  submissions/Chimoney-Slackbot/utils/app/__pycache__/views.cpython-39.pyc
  submissions/Chimoney-Slackbot/utils/app/models.py
  submissions/Chimoney-Slackbot/utils/app/mydatabase.db
  submissions/Chimoney-Slackbot/utils/app/views.py
  submissions/Chimoney-Slackbot/utils/bot.py
  submissions/Chimoney-Slackbot/utils/collation.py
  submissions/Chimoney-Slackbot/utils/functions.py
  submissions/Chimoney-Slackbot/utils/rtm.py
  submissions/Chimoney-Slackbot/utils/run.py
  submissions/Chisend/.gitignore
  submissions/Chisend/Dockerfile
  submissions/Chisend/bots/chisend.py
Labels: hacktoberfest, hacktoberfest-accepted

#312 Added Spanish Translation for Readme
  README-ES.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#331 [Feature]: Add sandbox support for chimoney js
  submissions/chimoney-js/index.js
  submissions/chimoney-js/readme.md
  submissions/chimoney-js/utils/helpers.js
Labels: hacktoberfest, hacktoberfest-accepted

#328 Chimoney GitHub integration
  submissions/chimoney-github-bot/.gitignore
  submissions/chimoney-github-bot/CODE_OF_CONDUCT.md
  submissions/chimoney-github-bot/CONTRIBUTING.md
  submissions/chimoney-github-bot/Dockerfile
  submissions/chimoney-github-bot/LICENSE
  submissions/chimoney-github-bot/README.md
  submissions/chimoney-github-bot/app.yml
  submissions/chimoney-github-bot/assets/payment_link.png
  submissions/chimoney-github-bot/assets/payout_command_usage.png
  submissions/chimoney-github-bot/assets/pr_merged_notification.png
  submissions/chimoney-github-bot/index.js
  submissions/chimoney-github-bot/package-lock.json
  submissions/chimoney-github-bot/package.json
  submissions/chimoney-github-bot/test/fixtures/issues.opened.json
  submissions/chimoney-github-bot/test/index.test.js
  submissions/chimoney-github-bot/utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#326 Translated blog post to markdown
  submissions/GetStarted/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#336 Enhancement: Github Bot enhancements
  submissions/chimoney-github-bot/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#334 Added Chinese Translation for README.md
  README-CN.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#333 Added Giveaway Feature
  submissions/Chimoney-Slackbot-V2/modules/choices.py
  submissions/Chimoney-Slackbot-V2/modules/giveaway.py
  submissions/Chimoney-Slackbot-V2/modules/validators.py
  submissions/Chimoney-Slackbot-V2/slackbot.py
Labels: hacktoberfest, hacktoberfest-accepted

#327 Create README-GM.md
  README-GM.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#329 Added Korean Translation for README.md
  README-KO.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
