Repository Chimoney/chimoney-community-projects, pull requests merged in 2024-10, with the labels that each got.

#423 updated the link for article submission folder in the README.md file
  README.md
Labels: hacktoberfest-accepted

#427 Added Badges Design for Every Merged PR
  submissions/Badges Designs/PR1.png
  submissions/Badges Designs/PR2.png
  submissions/Badges Designs/PR3.png
  submissions/Badges Designs/PR4.png
Labels: hacktoberfest-accepted

#431 Fixing placeholder and button for chimoney-redeem-airtime
  submissions/chimoney-redeem-airtime/src/components/Home.js
Labels: hacktoberfest-accepted

#397 Chimoney Readme Translator
  submissions/readme-translator/.github/workflow/translate.yml
  submissions/readme-translator/README.md
Labels: hacktoberfest-accepted

#421 Fixed Responsiveness Issue Of Chimoney Redeem Airtime Based On Issue #416
  submissions/chimoney-redeem-airtime/src/components/Home.js
Labels: hacktoberfest-accepted

#404 👕 refactor: Refactor handle_request method to improve robustness
  submissions/Chimoney-Python/build/lib/pychimoney/__init__.py
  submissions/Chimoney-Python/chimoney/Base.py
  submissions/Chimoney-Python/chimoney/Chimoney.py
  submissions/Chimoney-Python/chimoney/Payments.py
  submissions/Chimoney-Python/chimoney/__init__.py
Labels: hacktoberfest-accepted

#395 Added FAQs for chimoney developer toolkit
  submissions/FAQs/FAQs.md
Labels: hacktoberfest-accepted

#422 Create top-3-payments-solutions-ifeoluwa-favour
  submissions/Dev focused articles/top-3-payment-challenges-solutions-ifeoluwa-favour
Labels: hacktoberfest-accepted

#415 doc: A Chimoney Guide to Payouts for Digital Marketplaces
  submissions/Articles/payout-digital-marketplaces.md
Labels: hacktoberfest-accepted

#408 Developer's Guide to Choosing the Right API for Global Payouts
  submissions/Articles/GlobalPayoutGuide.md
Labels: hacktoberfest-accepted

#396 link the article for #382
  submissions/Articles/chimoney-global-data-annotators.md
Labels: hacktoberfest-accepted

#441 Add Documentation for Laravel SDK Installation and Usage
  submissions/chiconnect-laravel-web-app/Laravel SDK Installation and Setup Guide.md
Labels: hacktoberfest-accepted

#440 Improved the CONTRIBUTE.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#432 Refactoring handleWebhook to Improve Readability, Error Handling, and Modularity
  submissions/chimoney-discord-bot/controllers/webhook.controller.js
Labels: hacktoberfest

#434 automate badge distribution based on merged pr activity
  .github/badges/PR1.png
  .github/badges/PR2.png
  .github/badges/PR3.png
  .github/badges/PR4.png
  .github/scripts/badge-automation.js
  .github/workflows/badge-automation.yml
Labels: hacktoberfest-accepted

#402 Enhancement: Update Quickstart Guide
  README.md
  submissions/Articles/Quickstart_Guide.md
Labels: hacktoberfest-accepted

#458 Improved Homepage of redeem Airtime
  submissions/chimoney-redeem-airtime/src/components/Redeem.js
Labels: hacktoberfest

#461 Add Bengali (বাংলা) translation for the main README file
  README-BN.md
  README.md
Labels: hacktoberfest

#469 Updated Bangla documentation in the README based on issue #468
  README-BN.md
Labels: hacktoberfest-accepted

#462 Benja/chimoney react library
  submissions/chiconnect-giftcard-payout/pnpm-lock.yaml
  submissions/chimoney-react-components/.gitignore
  submissions/chimoney-react-components/README.md
  submissions/chimoney-react-components/package-lock.json
  submissions/chimoney-react-components/package.json
  submissions/chimoney-react-components/postcss.config.js
  submissions/chimoney-react-components/src/ChimoneyReactComponents.jsx
  submissions/chimoney-react-components/src/components/ChimoneyAccountUpdate.tsx
  submissions/chimoney-react-components/src/components/ChimoneyPaymentForm.tsx
  submissions/chimoney-react-components/src/components/ChimoneyTransactionList.tsx
  submissions/chimoney-react-components/src/components/chimoneyButton.tsx
  submissions/chimoney-react-components/src/components/chimoneyInput.tsx
  submissions/chimoney-react-components/src/index.js
  submissions/chimoney-react-components/src/styles/tailwind.css
  submissions/chimoney-react-components/tailwind.config.js
  submissions/chimoney-react-components/vite.config.js
Labels: hacktoberfest

#460 feat: Add AI-based Invoice Generation Method to Chimoney API Integration
  submissions/Chimoney-Python/chimoney/AI.py
Labels: hacktoberfest

#398 Telegram Bot
  submissions/chimoney-telegram/package.json
  submissions/chimoney-telegram/src/.env
  submissions/chimoney-telegram/src/payments.json
  submissions/chimoney-telegram/src/start.js
  submissions/chimoney-telegram/src/users.json
Labels: hacktoberfest, hacktoberfest-accepted
